### PR TITLE
Run make, which changes "draft" to "final" in the SRFI text

### PR DESCRIPTION
**Pull request by jpellegrini**
Also get a more modern HTML from pandoc...

### CODE REVIEW

**Comment by jpellegrini** [comment]
But it changes the format of drat and finalization dates (removes leading zero form day numbers)

**Comment by arthurgleckler** [comment]
Please don't do this.  It makes other changes, too.  I will fix "final" myself.

**Comment by jpellegrini** [comment]
Okay! (I would have filed an issue, but I see SRFIs don't use those, favoring the mailing lists - I'll tr to use the mailing lists in the future)

**Comment by arthurgleckler** [comment]
No problem, and thank you for reporting this one, too.  I'm going to have to do an audit of other SRFIs.

As you say, we favor the mailing lists.  We try not to use any of the non-Git features of Github in order to future-proof ourselves.  If we end up moving to another Git host, it will be much easier not to have to move other metadata.  Also, we have some users who are strict about using only free software, and who therefore won't use Github.

Anyway, thanks again for catching these details.

**Comment by jpellegrini** [comment]
Ok, so I suppose we can close this PR!
Thank you for quickly fixing the problems! :)

**Pull request closed without merging**
